service: DataCatalogueAPI

custom:
  project: dataplattform
  stage: ${opt:stage, self:provider.stage}
  service: ${self:custom.stage}-${self:service} #this service definition includes stage
  wsgi:
    app: app.app
    packRequirements: false
    pythonBin: python
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
  authorizer:
    type: COGNITO_USER_POOLS
    name: authorizer
    authorizerId: !Ref Authorizer
    scopes:
      - openid

provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${self:custom.stage}-${self:service}
  deploymentBucket:
    name: dataplattform-v2-deploymentbucket
  runtime: python3.7
  memorySize: 1024
  timeout: 10
  tags:
    project: ${self:custom.project}
    layer: API
  stackTags:
    project: ${self:custom.project}
    layer: API

package:
  individually: true
  exclude:
    - "./**"

functions:
  DataCatalogueAPI:
    handler: wsgi_handler.handler
    name: ${self:custom.stage}-${self:service}
    description: Dataplattform Data Catalogue API
    role: !ImportValue ${self:custom.stage}-assumeRole
    environment:
      STAGE: ${self:custom.stage}
    package:
      include:
        - '*.py'
        - '**/*.py'
    events:
      - http:
          method: GET
          path: /{proxy+}
          authorizer: ${self:custom.authorizer}
      - http:
          method: GET
          path: /
          authorizer: ${self:custom.authorizer}

resources:
  Resources:
    Authorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        IdentitySource: method.request.header.authorization
        Name: DataplattformDataAPIAuthorizer
        ProviderARNs:
          - !ImportValue ${self:custom.stage}-cognito-userPool
        RestApiId: !Ref ApiGatewayRestApi
        Type: COGNITO_USER_POOLS

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-pseudo-parameters