service: DataAPI

custom:
  project: dataplattform
  stage: ${opt:stage, self:provider.stage}
  service: ${self:custom.stage}-${self:service} #this service definition includes stage
  wsgi:
    app: app.app
    packRequirements: false
    pythonBin: python
  pythonRequirements:
    dockerizePip: true
    noDeploy:
      - boto3 # Default in lambda rt
      - botocore
      - numpy # Layer
      - numpy.libs
  authorizer:
    type: COGNITO_USER_POOLS
    name: authorizer
    authorizerId: !Ref Authorizer
    scopes:
      - openid # TODO scopes

provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${self:custom.stage}-${self:service}
  deploymentBucket:
    name: dataplattform-v2-deploymentbucket
  runtime: python3.7
  memorySize: 1024
  timeout: 10

  tags:
    project: ${self:custom.project}
    layer: API
  stackTags:
    project: ${self:custom.project}
    layer: API

package:
  individually: true
  exclude:
    - "./**"

functions:
  DataAPI:
    handler: wsgi_handler.handler
    layers:
      - !ImportValue ${self:custom.stage}-numpyDepLayer-arn
    name: ${self:custom.stage}-${self:service}
    description: Dataplattform Data API
    role: !ImportValue ${self:custom.stage}-assumeRole
    package:
      include:
        - '*.py'
    environment: 
      DATALAKE: !ImportValue ${self:custom.stage}-datalakeName
    events:
      - http:
          method: ANY
          path: /{proxy+}
          authorizer: ${self:custom.authorizer}
      - http:
          method: ANY
          path: /
          authorizer: ${self:custom.authorizer}
            

resources:
  Resources:
    Authorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        IdentitySource: method.request.header.authorization
        Name: DataplattformDataAPIAuthorizer
        ProviderARNs:
          - !ImportValue ${self:custom.stage}-cognito-userPool
        RestApiId: !Ref ApiGatewayRestApi
        Type: COGNITO_USER_POOLS

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-pseudo-parameters
