service: datalake

custom:
  project: dataplattform
  stage: ${opt:stage, self:provider.stage}
  service: ${self:custom.stage}-${self:service}
  default_level_3_staging_dir: data/level-3/athena-stage
  default_level_2_staging_dir: data/level-2/athena-stage
  default_level_1_staging_dir: data/level-1/athena-stage


provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${self:custom.service}
  deploymentBucket: #provide a bucket name to where serverless assets should to be uploaded
    name: ${self:custom.stage}-dataplattform-v2-deploymentbucket

  tags:
    project: dataplattform
    layer: infrastructure
  stackTags: #sets CloudFormation stack tags
    project: dataplattform
    layer: infrastructure

resources:
  Resources: 
    LogBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.service}-log-bucket
        VersioningConfiguration:
          Status: Enabled #keeps different versions of object if overwrited/updated
        AccessControl:
          LogDeliveryWrite

    DataLake:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.service}-datalake
        VersioningConfiguration:
          Status: Enabled #keeps different versions of object if overwrited/updated
        PublicAccessBlockConfiguration: #blocks any public access to s3 bucket
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        LifecycleConfiguration:
          Rules:
            - ExpirationInDays: 7
              NoncurrentVersionExpirationInDays: 7
              Prefix: ${self:custom.default_level_3_staging_dir}
              Status: Enabled
            - ExpirationInDays: 7
              NoncurrentVersionExpirationInDays: 7
              Prefix: ${self:custom.default_level_2_staging_dir}
              Status: Enabled
            - ExpirationInDays: 7
              NoncurrentVersionExpirationInDays: 7
              Prefix: ${self:custom.default_level_1_staging_dir}
              Status: Enabled
        LoggingConfiguration:
          DestinationBucketName: ${self:resources.Resources.LogBucket.Properties.BucketName}
          LogFilePrefix: ${self:resources.Resources.LogBucket.Properties.BucketName}

  #Arn of S3 bucket needs to be exported in order to use it from other services (ingestion and processing)
  Outputs:
    DataLakeArn:
      Value: !GetAtt DataLake.Arn
      Export:
        Name: ${self:custom.stage}-datalakeArn
    DataLakeName:
      Value: ${self:resources.Resources.DataLake.Properties.BucketName}
      Export:
        Name: ${self:custom.stage}-datalakeName
    Level3StagingDir:
      Value: ${self:custom.default_level_3_staging_dir}
      Export:
        Name: ${self:custom.stage}-default-level-3-staging_dir
    Level2StagingDir:
      Value: ${self:custom.default_level_2_staging_dir}
      Export:
        Name: ${self:custom.stage}-default-level-2-staging_dir
    Level1StagingDir:
      Value: ${self:custom.default_level_1_staging_dir}
      Export:
        Name: ${self:custom.stage}-default-level-1-staging_dir
    LogBucketName:
      Value: ${self:resources.Resources.LogBucket.Properties.BucketName}
      Export:
        Name: ${self:custom.stage}-logBucketName