Resources:
  DoraWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: DoraWorkgroups
      Description: Workgroup for DORA views
      State: ENABLED
      WorkGroupConfiguration:
        ResultConfiguration:
          OutputLocation: s3://dev-kmsbucket-876363704293/Athena-logs/
          EncryptionConfiguration: 
            EncryptionOption: SSE_KMS
            KmsKey: 
              Fn::Join:
                - ""
                - - "arn:aws:kms:#{AWS::Region}:#{AWS::AccountId}:key/"
                  - !ImportValue ${self:custom.stage}-KMS-KeyID
  AthenaSetupRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.stage}-${self:service}-Athena-Setup-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        Policies:
          - PolicyName: ${self:custom.stage}-Glue-${self:service}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - 'glue:GetTable'
                    - 'glue:GetDatabase'
                  Resource:
                    - !Sub 'arn:aws:glue:#{AWS::Region}:#{AWS::AccountId}:catalog'
                    - !Sub 'arn:aws:glue:#{AWS::Region}:#{AWS::AccountId}:database/${self:custom.stage}_${self:custom.editable.databaseName}_database'
                    - !Sub 'arn:aws:glue:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.stage}_${self:custom.editable.databaseName}_database/*'
          - PolicyName: ${self:custom.stage}-EncryptedBucketKMS-${self:service}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - kms:Encrypt
                    - kms:Decrypt
                    - kms:DescribeKey
                    - kms:ListKeys
                    - kms:GenerateDataKey 
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:kms:#{AWS::Region}:#{AWS::AccountId}:key/"
                        - !ImportValue ${self:custom.stage}-KMS-KeyID 
          - PolicyName: ${self:custom.stage}-Athena-${self:service}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - 'athena:StartQueryExecution'
                    - 'athena:GetQueryExecution'
                    - 'athena:GetQueryResults'
                    - 'athena:ListNamedQueries'
                    - 'athena:GetNamedQuery'
                    - 'athena:CreateNamedQuery'
                  Resource:
                    !Sub 'arn:aws:athena:#{AWS::Region}:#{AWS::AccountId}:workgroup/DoraWorkgroups'
          - PolicyName: ${self:custom.stage}-DatalakeIO-${self:service}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:ListObjects*
                    - s3:GetObject
                    - s3:CopyObject
                    - s3:DeleteObjects
                    - s3:DeleteObjectVersion
                    - s3:DeleteObject
                  Resource:
                    - !Sub arn:aws:s3:::${self:custom.stage}-kmsbucket-${AWS::AccountId}
                    - !Sub arn:aws:s3:::${self:custom.stage}-kmsbucket-${AWS::AccountId}*