Resources:
  CrawlerLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      KmsKeyId:
        Fn::Join:
          - ""
          - - "arn:aws:kms:#{AWS::Region}:#{AWS::AccountId}:key/"
            - !ImportValue ${self:custom.stage}-KMS-KeyID
      LogGroupName: /aws-glue/crawlers-role/Level4GlueRole-KMSGlueEncryptionConfigurations
