Resources:
  AthenaDataSource:
    Type: AWS::QuickSight::DataSource
    Properties:
      DataSourceParameters: 
        AthenaParameters:
          WorkGroup: DoraWorkgroups
      AwsAccountId: !Sub ${AWS::AccountId}
      Name: DoraWorkGroup-AthenaSources
      Type: ATHENA
      DataSourceId: DoraWorkGroup-AthenaID
      Permissions:
        - Principal: ${ssm:/dev/dora/quicksight_principal}
          Actions:
            - quicksight:UpdateDataSourcePermissions
            - quicksight:DescribeDataSource
            - quicksight:DescribeDataSourcePermissions
            - quicksight:PassDataSource
            - quicksight:UpdateDataSource
            - quicksight:DeleteDataSource
  S3DataSource:
    Type: AWS::QuickSight::DataSource
    Properties:
      AwsAccountId: !Sub ${AWS::AccountId}
      Name: DoraWorkGroup-S3DataSource
      Type: S3
      DataSourceId: S3Source
      DataSourceParameters: 
        S3Parameters:
          ManifestFileLocation:
            Bucket: dev-datalake-bucket-876363704293 #Update to accurate location
            Key: data/Manifest-S3.json #Update to accurate location
      Permissions:
        - Principal: ${ssm:/dev/dora/quicksight_principal}
          Actions:
            - quicksight:UpdateDataSourcePermissions
            - quicksight:DescribeDataSource
            - quicksight:DescribeDataSourcePermissions
            - quicksight:PassDataSource
            - quicksight:UpdateDataSource
            - quicksight:DeleteDataSource
  Rolebindings:
    Type: AWS::QuickSight::DataSet
    Properties:
      AwsAccountId: !Sub ${AWS::AccountId}
      DataSetId: Rolebinding
      Name: Rolebinding
      ImportMode: SPICE
      PhysicalTableMap:
        s3PhysicalTable:
          S3Source:
            DataSourceArn: !GetAtt S3DataSource.Arn
            InputColumns: 
              - Name: partition_1
                Type: STRING
              - Name: UserName
                Type: STRING
            UploadSettings:
              Format: CSV
              StartFromRow: 1
              ContainsHeader: True
              Delimiter: ','
      Permissions:
        - Principal: ${ssm:/dev/dora/quicksight_principal}
          Actions:
            - quicksight:UpdateDataSetPermissions
            - quicksight:DescribeDataSet
            - quicksight:DescribeDataSetPermissions
            - quicksight:PassDataSet
            - quicksight:DescribeIngestion
            - quicksight:ListIngestions
            - quicksight:UpdateDataSet
            - quicksight:DeleteDataSet
            - quicksight:CreateIngestion
            - quicksight:CancelIngestion
  DeploymentFrequency:
    Type: AWS::QuickSight::DataSet
    Properties:
      AwsAccountId: !Sub ${AWS::AccountId}
      DataSetId: DeploymentFrequency-id
      Name: DeploymentFrequency-id
      ImportMode: SPICE
      PhysicalTableMap:
        deploymentfreq:
          CustomSql:
            DataSourceArn: !GetAtt AthenaDataSource.Arn
            Name: deploymentFrequency
            SqlQuery: 'SELECT * FROM AwsDataCatalog.dev_level_4_database.deploymentfrequency'
            Columns:
              - Name: partition_1
                Type: STRING
              - Name: frequency
                Type: STRING
      RowLevelPermissionDataSet:
        Arn: !GetAtt Rolebindings.Arn
        FormatVersion: VERSION_1
        PermissionPolicy: GRANT_ACCESS
      Permissions:
        - Principal: ${ssm:/dev/dora/quicksight_principal}
          Actions:
            - quicksight:UpdateDataSetPermissions
            - quicksight:DescribeDataSet
            - quicksight:DescribeDataSetPermissions
            - quicksight:PassDataSet
            - quicksight:DescribeIngestion
            - quicksight:ListIngestions
            - quicksight:UpdateDataSet
            - quicksight:DeleteDataSet
            - quicksight:CreateIngestion
            - quicksight:CancelIngestion
  DeploymentsNullValues:
    Type: AWS::QuickSight::DataSet
    Properties:
      AwsAccountId: !Sub ${AWS::AccountId}
      DataSetId: DeploymentsNullValues-id
      Name: DeploymentsNullValues-id
      ImportMode: SPICE
      PhysicalTableMap:
        deploymentfreq:
          CustomSql:
            DataSourceArn: !GetAtt AthenaDataSource.Arn
            Name: DeploymentsNullValues
            SqlQuery: 'SELECT * FROM AwsDataCatalog.dev_level_4_database.github_deployments_with_null_values'
            Columns:
              - Name: date_column
                Type: DATETIME 
              - Name: partition_1
                Type: STRING
              - Name: deployments
                Type: INTEGER 
      RowLevelPermissionDataSet:
        Arn: !GetAtt Rolebindings.Arn
        FormatVersion: VERSION_1
        PermissionPolicy: GRANT_ACCESS
      Permissions:
        - Principal: ${ssm:/dev/dora/quicksight_principal}
          Actions:
            - quicksight:UpdateDataSetPermissions
            - quicksight:DescribeDataSet
            - quicksight:DescribeDataSetPermissions
            - quicksight:PassDataSet
            - quicksight:DescribeIngestion
            - quicksight:ListIngestions
            - quicksight:UpdateDataSet
            - quicksight:DeleteDataSet
            - quicksight:CreateIngestion
            - quicksight:CancelIngestion