Resources:
  DataSources:
    Type: AWS::QuickSight::DataSource
    Properties:
      DataSourceParameters: 
        AthenaParameters:
          WorkGroup: DoraWorkgroups
      AwsAccountId: !Sub ${AWS::AccountId}
      Name: DoraWorkGroup-sources
      Type: ATHENA
      DataSourceId: DoraWorkGroupid
      Permissions:
        - Principal: ${ssm:/dev/dora/quicksight_principal}
          Actions:
            - quicksight:UpdateDataSourcePermissions
            - quicksight:DescribeDataSource
            - quicksight:DescribeDataSourcePermissions
            - quicksight:PassDataSource
            - quicksight:UpdateDataSource
            - quicksight:DeleteDataSource
  S3DataSource:
    Type: AWS::QuickSight::DataSource
    Properties:
      AwsAccountId: !Sub ${AWS::AccountId}
      Name: DoraWorkGroup-S3DataSource
      Type: S3
      DataSourceId: S3Source
      DataSourceParameters: 
        S3Parameters:
          ManifestFileLocation:
            Bucket: dev-datalake-bucket-876363704293 #Update to accurate location
            Key: data/Manifest-S3.json #Update to accurate location
      Permissions:
        - Principal: ${ssm:/dev/dora/quicksight_principal}
          Actions:
            - quicksight:UpdateDataSourcePermissions
            - quicksight:DescribeDataSource
            - quicksight:DescribeDataSourcePermissions
            - quicksight:PassDataSource
            - quicksight:UpdateDataSource
            - quicksight:DeleteDataSource
  Rolebindings:
    Type: AWS::QuickSight::DataSet
    Properties:
      AwsAccountId: !Sub ${AWS::AccountId}
      DataSetId: Rolebinding-test
      Name: Rolebinding-test
      ImportMode: SPICE
      PhysicalTableMap:
        s3PhysicalTable:
          S3Source:
            DataSourceArn: !Sub arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:datasource/S3Source
            InputColumns: 
              - Name: partition_1
                Type: STRING
              - Name: UserName
                Type: STRING
            UploadSettings:
              Format: CSV
              StartFromRow: 1
              ContainsHeader: True
              Delimiter: ','
      Permissions:
        - Principal: ${ssm:/dev/dora/quicksight_principal}
          Actions:
            - quicksight:UpdateDataSetPermissions
            - quicksight:DescribeDataSet
            - quicksight:DescribeDataSetPermissions
            - quicksight:PassDataSet
            - quicksight:DescribeIngestion
            - quicksight:ListIngestions
            - quicksight:UpdateDataSet
            - quicksight:DeleteDataSet
            - quicksight:CreateIngestion
            - quicksight:CancelIngestion