service: metadata

custom:
  stage: ${opt:stage, self:provider.stage}
  service: ${self:custom.stage}-${self:service}

provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${self:custom.service}
  deploymentBucket: #provide a bucket name to where serverless assets should to be uploaded
    name: ${self:custom.stage}-dataplattform-v2-deploymentbucket

resources:
  Resources:
    PersonalMetadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stage}_personal_metadata_table
        AttributeDefinitions:
          - AttributeName: guid
            AttributeType: S
        KeySchema:
          - AttributeName: guid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        SSESpecification:
          SSEEnabled: True
          SSEType: KMS
          KMSMasterKeyId: de8ca893-e2fc-4f8c-83b1-bc41a9a3a79a


    PersonalMetadataTableAccess:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: Access to ${self:custom.stage} Personal Metadata Table
        ManagedPolicyName: ${self:custom.stage}-personal-metadata-table
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Batch*
                - dynamodb:DescribeTable
              Resource: !GetAtt PersonalMetadataTable.Arn

  Outputs:
    PersonalMetadataTableAccessOutput:
      Value:
        Ref: PersonalMetadataTableAccess
      Export:
        Name: ${self:custom.stage}-personal-metadata-table-access-policy
    PersonalMetadataTableName:
      Value: ${self:resources.Resources.PersonalMetadataTable.Properties.TableName}
      Export:
        Name: ${self:custom.stage}-personal-metadata-table-name
    PersonalMetadataTableArn:
      Value: !GetAtt PersonalMetadataTable.Arn
      Export:
        Name: ${self:custom.stage}-personal-metadata-tableArn