  on: push
    name: Notify on Slack
    jobs: 
      slackNotification:
        name: Slack Notifications
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Slack Notifications
          uses: adamkdean/simple-slack-notify@master
        env:
          # required
           SLACK_WEBHOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}