name: Notify on Slack
on: push
jobs: 
  slackNotification:
    name: Slack Notifications 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notifications
        uses: adamkdean/simple-slack-notify@master
        env:
          # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: 'dataplattform_deployment'
          status: ${{ job.status }}
          success_text: 'Deployment (#${env.GITHUB_RUN_NUMBER}) completed successfully'
          failure_text: 'Deployment (#${env.GITHUB_RUN_NUMBER}) failed'
          cancelled_text: 'Deployment (#${env.GITHUB_RUN_NUMBER}) was cancelled'
          fields: |
            [{ "title": "Host", "value": "${{ secrets.DEPLOY_HOST }}"},
            { "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
