on: push
name: Slack Notification
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}     
        SLACK_CHANNEL: dataplattform_deployment
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_TITLE: ${{ env.GITHUB_WORKFLOW }}
        SLACK_USERNAME: Dataplattform Deployment
      with: 
        success_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) build completed successfully'
        failure_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) build failed'
        cancelled_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) build was cancelled'
        fields: |
          [{ "title": "Repository", "value": "${env.GITHUB_REPOSITORY}", "short": true },
          { "title": "Branch", "value": "${env.BRANCH}", "short": true }]      

      